preset: angular
branches:
  - main
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - publishCmd: |
        tag="v${nextRelease.version}"
        git tag "$tag"
        GORELEASER_CURRENT_TAG="$tag" goreleaser release --clean
