package compose

import (
	"strings"
	"testing"
)

const (
	testImageNginx = "nginx:latest"
	errFmtEmit     = "Emit error: %v"
)

func TestNewFile(t *testing.T) {
	f := NewFile()
	if f.Services == nil {
		t.Fatal("Services should be initialized")
	}
	if f.Volumes == nil {
		t.Fatal("Volumes should be initialized")
	}
	if f.Networks == nil {
		t.Fatal("Networks should be initialized")
	}
	if f.Configs == nil {
		t.Fatal("Configs should be initialized")
	}
}

func TestNewService(t *testing.T) {
	svc := NewService(testImageNginx)
	if svc.Image != testImageNginx {
		t.Errorf("Image = %q", svc.Image)
	}
	if svc.Environment == nil {
		t.Fatal("Environment should be initialized")
	}
	if svc.DependsOn == nil {
		t.Fatal("DependsOn should be initialized")
	}
	if svc.Labels == nil {
		t.Fatal("Labels should be initialized")
	}
}

func TestEmit_MinimalService(t *testing.T) {
	f := NewFile()
	f.Project = "test"
	f.Services["web"] = NewService(testImageNginx)

	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}

	if !strings.Contains(out, "name: test") {
		t.Error("missing project name")
	}
	if !strings.Contains(out, "web:") {
		t.Error("missing service name")
	}
	if !strings.Contains(out, "image: nginx:latest") {
		t.Error("missing image")
	}
}

func TestEmit_Header(t *testing.T) {
	f := NewFile()
	f.Header = "Generated by composed"
	f.Services["app"] = NewService("myapp:latest")

	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}

	if !strings.Contains(out, "# Generated by composed") {
		t.Errorf("missing header comment in output:\n%s", out)
	}
}

func TestEmit_FullService(t *testing.T) {
	f := NewFile()
	f.Project = "test"

	svc := NewService("myapp:latest")
	svc.Entrypoint = []string{"/bin/sh", "-c"}
	svc.Command = []string{"serve", "--port=8080"}
	svc.Environment["PORT"] = "8080"
	svc.Environment["DEBUG"] = "true"
	svc.Ports = []string{"8080:8080", "9090:9090"}
	svc.Volumes = []string{"data:/data"}
	svc.Tmpfs = []string{"/tmp"}
	svc.ShmSize = "256m"
	svc.Restart = "unless-stopped"
	svc.Labels["team"] = "backend"
	svc.Profiles = []string{"dev"}
	svc.DependsOn["postgres"] = DependsOnCondition{Condition: "service_healthy"}
	svc.Healthcheck = &Healthcheck{
		Test:        []string{"CMD", "curl", "-f", "http://localhost:8080/health"},
		Interval:    "10s",
		Timeout:     "5s",
		Retries:     3,
		StartPeriod: "30s",
	}
	replicas := 2
	svc.Deploy = &Deploy{
		Replicas: &replicas,
		Resources: &Resources{
			Limits:       &ResourceSpec{CPUs: "1.00", Memory: "512M"},
			Reservations: &ResourceSpec{CPUs: "0.25", Memory: "128M"},
		},
	}
	svc.Configs = []ServiceConfig{{Source: "my-config", Target: "/etc/app/config.yaml"}}

	f.Services["app"] = svc
	f.Volumes["data"] = &Volume{}
	f.Networks["frontend"] = &Network{}
	f.Configs["my-config"] = &Config{Content: "key: value"}

	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}

	checks := []string{
		"name: test",
		"app:",
		"image: myapp:latest",
		"entrypoint:",
		"/bin/sh",
		"command:",
		"serve",
		"environment:",
		"PORT: 8080",
		"ports:",
		"8080:8080",
		"volumes:",
		"data:/data",
		"tmpfs:",
		"/tmp",
		"shm_size: 256m",
		"depends_on:",
		"postgres:",
		"condition: service_healthy",
		"healthcheck:",
		"test:",
		"CMD",
		"interval: 10s",
		"timeout: 5s",
		"retries: 3",
		"start_period: 30s",
		"deploy:",
		"replicas: 2",
		"resources:",
		"limits:",
		"cpus: 1.00",
		"memory: 512M",
		"reservations:",
		"restart: unless-stopped",
		"profiles:",
		"dev",
		"labels:",
		"team: backend",
		"volumes:",
		"data:",
		"networks:",
		"frontend:",
		"configs:",
		"my-config:",
		"content:",
		"key: value",
	}

	for _, check := range checks {
		if !strings.Contains(out, check) {
			t.Errorf("missing %q in output:\n%s", check, out)
		}
	}
}

func TestEmit_DeterministicOrder(t *testing.T) {
	f := NewFile()
	f.Services["zebra"] = NewService("zebra:latest")
	f.Services["alpha"] = NewService("alpha:latest")
	f.Services["middle"] = NewService("middle:latest")

	out1, _ := Emit(f)
	out2, _ := Emit(f)

	if out1 != out2 {
		t.Error("Emit should produce deterministic output")
	}

	// alpha should come before middle, middle before zebra
	alphaIdx := strings.Index(out1, "alpha:")
	middleIdx := strings.Index(out1, "middle:")
	zebraIdx := strings.Index(out1, "zebra:")

	if alphaIdx > middleIdx || middleIdx > zebraIdx {
		t.Errorf("services not in alphabetical order: alpha=%d, middle=%d, zebra=%d",
			alphaIdx, middleIdx, zebraIdx)
	}
}

func TestEmit_Volumes(t *testing.T) {
	f := NewFile()
	f.Services["app"] = NewService("app:latest")
	f.Volumes["data"] = &Volume{}
	f.Volumes["custom"] = &Volume{Driver: "nfs"}

	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}

	if !strings.Contains(out, "data:") {
		t.Error("missing data volume")
	}
	if !strings.Contains(out, "driver: nfs") {
		t.Error("missing custom driver for volume")
	}
}

func TestEmit_RestartPolicy(t *testing.T) {
	f := NewFile()
	svc := NewService("job:latest")
	svc.Deploy = &Deploy{
		RestartPolicy: &RestartPolicy{
			Condition:   "on-failure",
			MaxAttempts: 3,
		},
	}
	f.Services["job"] = svc

	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}

	if !strings.Contains(out, "restart_policy:") {
		t.Error("missing restart_policy")
	}
	if !strings.Contains(out, "condition: on-failure") {
		t.Error("missing condition")
	}
	if !strings.Contains(out, "max_attempts: 3") {
		t.Error("missing max_attempts")
	}
}

func TestEmit_ConfigFile(t *testing.T) {
	f := NewFile()
	f.Services["app"] = NewService("app:latest")
	f.Configs["from-file"] = &Config{File: "./config.yaml"}

	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}

	if !strings.Contains(out, "file: ./config.yaml") {
		t.Error("missing file config")
	}
}

func TestEmit_EmptyFile(t *testing.T) {
	f := NewFile()
	out, err := Emit(f)
	if err != nil {
		t.Fatalf(errFmtEmit, err)
	}
	// Should produce valid YAML with no services/volumes/etc
	if strings.Contains(out, "services:") {
		t.Error("empty file should not have services section")
	}
}
