// Package compose defines the Docker Compose file model and YAML emitter.
package compose

// File represents a complete docker-compose.yaml.
type File struct {
	// Header comment (e.g. "Generated by composed from composed.yaml")
	Header string

	// Project name (maps to COMPOSE_PROJECT_NAME / top-level `name:`)
	Project string

	Services map[string]*Service
	Volumes  map[string]*Volume
	Networks map[string]*Network
	Configs  map[string]*Config
}

// Service represents a single compose service.
type Service struct {
	Image       string
	Entrypoint  []string
	Command     []string
	Environment map[string]string
	Ports       []string
	Volumes     []string // "name:/path" or "/host:/container"
	Tmpfs       []string // tmpfs mounts (e.g. "/dev/shm")
	DependsOn   map[string]DependsOnCondition
	Healthcheck *Healthcheck
	Deploy      *Deploy
	Configs     []ServiceConfig
	Labels      map[string]string
	Restart     string // "unless-stopped", "no", "on-failure", etc.
	Profiles    []string
	ShmSize     string // e.g. "64m"
}

type DependsOnCondition struct {
	Condition string // "service_started", "service_healthy", "service_completed_successfully"
}

type Healthcheck struct {
	Test        []string // ["CMD", ...] or ["CMD-SHELL", "..."]
	Interval    string
	Timeout     string
	Retries     int
	StartPeriod string
}

type Deploy struct {
	Replicas      *int
	Resources     *Resources
	RestartPolicy *RestartPolicy
}

type Resources struct {
	Limits       *ResourceSpec
	Reservations *ResourceSpec
}

type ResourceSpec struct {
	CPUs   string // "0.5", "2.0"
	Memory string // "256M", "1G"
}

type RestartPolicy struct {
	Condition   string // "none", "on-failure", "any"
	MaxAttempts int
}

type Volume struct {
	Driver string // default: "local"
	// Labels or driver_opts could be added later
}

type Network struct {
	Driver string // default: "bridge"
}

type Config struct {
	Content string // inline content
	File    string // or path to file
}

type ServiceConfig struct {
	Source string
	Target string
}

// NewFile returns an empty Compose file with initialized maps.
func NewFile() *File {
	return &File{
		Services: make(map[string]*Service),
		Volumes:  make(map[string]*Volume),
		Networks: make(map[string]*Network),
		Configs:  make(map[string]*Config),
	}
}

// NewService returns a service with initialized maps/slices.
func NewService(image string) *Service {
	return &Service{
		Image:       image,
		Environment: make(map[string]string),
		DependsOn:   make(map[string]DependsOnCondition),
		Labels:      make(map[string]string),
	}
}
