package cmd

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/docker-x/composed/internal/compose"
	"github.com/docker-x/composed/internal/config"
	"github.com/docker-x/composed/internal/helm"
	"github.com/docker-x/composed/internal/merge"
	"github.com/docker-x/composed/internal/translate"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

const defaultOutputFile = "docker-compose.yaml"

var buildCmd = &cobra.Command{
	Use:   "build",
	Short: "Build a mega docker-compose.yaml from a composed.yaml config",
	Long: `Read a composed.yaml (a Docker Compose file with x- extensions) and
produce a single merged docker-compose.yaml. Helm charts are rendered,
compose includes are merged, and cross-references are resolved.

Services can reference each other via ${service.export_key} syntax
using x-exports, similar to Terraform or CDK.

Examples:
  # Build from config
  composed build -f composed.yaml -o docker-compose.yaml

  # Build and immediately start
  composed up -f composed.yaml`,
	RunE: runBuild,
}

var (
	buildFile   string
	buildOutput string
	upFile      string
	upOutput    string
	downOutput  string
)

var upCmd = &cobra.Command{
	Use:   "up",
	Short: "Build and start the stack via docker compose up",
	RunE:  runUp,
}

var downCmd = &cobra.Command{
	Use:   "down",
	Short: "Stop the stack via docker compose down",
	RunE:  runDown,
}

func init() {
	buildCmd.Flags().StringVarP(&buildFile, "file", "f", "composed.yaml", "Config file")
	buildCmd.Flags().StringVarP(&buildOutput, "output", "o", defaultOutputFile, "Output file (- for stdout)")
	rootCmd.AddCommand(buildCmd)

	upCmd.Flags().StringVarP(&upFile, "file", "f", "composed.yaml", "Config file")
	upCmd.Flags().StringVarP(&upOutput, "output", "o", defaultOutputFile, "Output file")
	downCmd.Flags().StringVarP(&downOutput, "output", "o", defaultOutputFile, "Compose file")
	rootCmd.AddCommand(upCmd)
	rootCmd.AddCommand(downCmd)
}

func runBuild(cmd *cobra.Command, args []string) error {
	buildFile = resolveConfig(cmd, buildFile)
	return doBuild()
}

func runUp(cmd *cobra.Command, args []string) error {
	buildFile = resolveConfig(cmd, upFile)
	buildOutput = upOutput
	if err := doBuild(); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Starting stack with docker compose up -d ...\n")
	return dockerCompose("up", "-d")
}

func runDown(cmd *cobra.Command, args []string) error {
	buildOutput = downOutput
	fmt.Fprintf(os.Stderr, "Stopping stack ...\n")
	return dockerCompose("down")
}

func doBuild() error {
	// 1. Load config
	cfg, err := config.Load(buildFile)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	// 2. Run top-level x-shell entries (before ref resolution)
	shellValues, err := config.RunShellEntries(cfg.XShell)
	if err != nil {
		return err
	}

	// 2b. Pre-load env_file vars and compose-component environment into
	// config services so ResolveRefs can see them for cross-references.
	origEnvKeys := snapshotEnvKeys(cfg)
	preloadServiceEnvFiles(cfg)
	preloadComposeExports(cfg)

	// 3. Resolve cross-references (pass shell values for ${name} lookups)
	if refErr := cfg.ResolveRefs(shellValues); refErr != nil {
		return fmt.Errorf("resolve refs: %w", refErr)
	}

	// 3b. Strip preloaded env keys — keep only what composed.yaml declared.
	stripPreloadedEnvKeys(cfg, origEnvKeys)

	// 4. Process each service → compose fragment
	fragments, err := processServices(cfg)
	if err != nil {
		return err
	}

	// 5. Merge all fragments
	merged := merge.Merge(cfg.Name, fragments...)

	// 6. Apply user-declared volumes (override chart-generated ones)
	applyConfigVolumes(merged, cfg)

	// 7. Label all services as composed-managed
	labelServices(merged, cfg)

	// 8. Set header
	names := make([]string, 0, len(cfg.Services))
	for n := range cfg.Services {
		names = append(names, n)
	}
	sort.Strings(names)
	merged.Header = fmt.Sprintf("Generated by composed from %s\n# Components: %s",
		buildFile, strings.Join(names, ", "))

	// 9. Emit
	return emitOutput(merged)
}

// snapshotEnvKeys records the original environment keys per service
// so preloaded keys can be stripped after ref resolution.
func snapshotEnvKeys(cfg *config.File) map[string]map[string]bool {
	origEnvKeys := make(map[string]map[string]bool)
	for name := range cfg.Services {
		keys := make(map[string]bool)
		for k := range cfg.Services[name].Environment {
			keys[k] = true
		}
		origEnvKeys[name] = keys
	}
	return origEnvKeys
}

// stripPreloadedEnvKeys removes environment keys that were added by
// preloadServiceEnvFiles / preloadComposeExports — they were only
// needed for cross-reference resolution, not for the output.
func stripPreloadedEnvKeys(cfg *config.File, origEnvKeys map[string]map[string]bool) {
	for name := range cfg.Services {
		svc := cfg.Services[name]
		if svc.Environment == nil {
			continue
		}
		for k := range svc.Environment {
			if !origEnvKeys[name][k] {
				delete(svc.Environment, k)
			}
		}
		if len(svc.Environment) == 0 {
			svc.Environment = nil
		}
		cfg.Services[name] = svc
	}
}

// emitOutput writes the merged compose file to the configured output.
func emitOutput(merged *compose.File) error {
	out, err := compose.Emit(merged)
	if err != nil {
		return fmt.Errorf("emit: %w", err)
	}

	if buildOutput == "-" {
		fmt.Print(out)
		return nil
	}

	if err := os.WriteFile(buildOutput, []byte(out), 0644); err != nil {
		return fmt.Errorf("write %s: %w", buildOutput, err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %s (%d services, %d volumes)\n",
		buildOutput, len(merged.Services), len(merged.Volumes))
	return nil
}

func processServices(cfg *config.File) ([]*compose.File, error) {
	var fragments []*compose.File

	order := topoSort(cfg)
	for _, name := range order {
		svc := cfg.Services[name]
		svcType := config.ServiceType(&svc)

		fmt.Fprintf(os.Stderr, "Processing service %q (type: %s)...\n", name, svcType)

		var frag *compose.File
		var fragErr error

		switch svcType {
		case "image":
			frag = imageToCompose(name, &svc)
		case "compose":
			frag, fragErr = composeFragment(&svc)
		case "helm":
			frag, fragErr = helmToCompose(name, &svc)
		default:
			return nil, fmt.Errorf("service %q: unknown type %q", name, svcType)
		}
		if fragErr != nil {
			return nil, fmt.Errorf("service %q: %w", name, fragErr)
		}

		// Apply cross-service depends_on
		if len(svc.DependsOn) > 0 && frag != nil {
			applyDependsOn(frag, svc.DependsOn, cfg)
		}

		// Overlay user-specified fields from composed.yaml onto generated services
		// (for helm/compose types, user may add environment, volumes, env_file, etc.)
		if svcType != "image" && frag != nil {
			overlayServiceFields(frag, name, &svc)
		}

		fragments = append(fragments, frag)
	}

	return fragments, nil
}

// overlayServiceFields merges user-specified fields from composed.yaml onto
// generated services (helm/compose). Targets the primary service matching the
// composed.yaml service name. Environment vars are merged (user wins),
// volumes and env_file are appended.
func overlayServiceFields(frag *compose.File, name string, svc *config.Service) {
	target, ok := frag.Services[name]
	if !ok {
		// Helm charts may not produce a service with the exact name;
		// if there's only one service, use it.
		// target is a *Service pointer, so mutations are reflected in frag.Services.
		if len(frag.Services) == 1 {
			for _, s := range frag.Services {
				target = s
			}
		}
		if target == nil {
			return
		}
	}

	// Override command if user specifies it
	if len(svc.Command) > 0 {
		target.Command = svc.Command
	}

	// Merge environment (user wins on conflict)
	for k, v := range svc.Environment {
		target.Environment[k] = v
	}

	// Append env_file
	target.EnvFile = append(target.EnvFile, svc.EnvFile...)

	// Append volumes
	target.Volumes = append(target.Volumes, svc.Volumes...)

	// Append ports (if user specifies additional)
	target.Ports = append(target.Ports, svc.Ports...)
}

// preloadServiceEnvFiles parses env_file entries declared in composed.yaml
// and loads their KEY=VALUE pairs into each service's Environment map.
// Inline environment entries always win (fill-gaps only).
func preloadServiceEnvFiles(cfg *config.File) {
	cfgDir := filepath.Dir(buildFile)
	for name := range cfg.Services {
		svc := cfg.Services[name]
		if len(svc.EnvFile) == 0 {
			continue
		}
		svc.Environment = loadEnvFilesInto(svc.Environment, svc.EnvFile, cfgDir)
		cfg.Services[name] = svc
	}
}

// loadEnvFilesInto loads KEY=VALUE pairs from env files into the given
// environment map (creating it if nil). Existing keys are never overwritten.
func loadEnvFilesInto(env map[string]string, files []string, baseDir string) map[string]string {
	if env == nil {
		env = make(map[string]string)
	}
	for _, ef := range files {
		p := ef
		if !filepath.IsAbs(p) {
			p = filepath.Join(baseDir, p)
		}
		for k, v := range loadEnvFile(p) {
			if _, exists := env[k]; !exists {
				env[k] = v
			}
		}
	}
	return env
}

// preloadComposeExports reads x-compose-file targets and copies their
// x-exports, environment, and env_file vars into the config services.
// This allows ResolveRefs to resolve ${svc.environment.KEY} and
// ${svc.key} (from x-exports) for compose-file components.
// Component values only fill gaps — composed.yaml entries always win.
func preloadComposeExports(cfg *config.File) {
	for name := range cfg.Services {
		svc := cfg.Services[name]
		if svc.XComposeFile == "" {
			continue
		}
		if preloadOneComposeExport(&svc, name) {
			cfg.Services[name] = svc
		}
	}
}

// preloadOneComposeExport loads x-exports and environment from a single
// x-compose-file component into the config service. Returns true if svc was modified.
func preloadOneComposeExport(svc *config.Service, name string) bool {
	path := svc.XComposeFile
	if !filepath.IsAbs(path) {
		path = filepath.Join(filepath.Dir(buildFile), path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: cannot read component %s for %q: %v\n", path, name, err)
		return false
	}
	var raw struct {
		Services map[string]rawServiceStruct `yaml:"services"`
	}
	if err := yamlUnmarshal(data, &raw); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: cannot parse component %s for %q: %v\n", path, name, err)
		return false
	}
	target, found := findRawService(raw.Services, name)
	if !found {
		return false
	}

	// 1. Merge x-exports per key (component fills gaps only)
	if len(target.XExports) > 0 {
		if svc.XExports == nil {
			svc.XExports = make(map[string]string)
		}
		for k, v := range target.XExports {
			if _, exists := svc.XExports[k]; !exists {
				svc.XExports[k] = v
			}
		}
	}

	// 2. Load component's environment + env_file into config for ref resolution.
	compEnv := buildComponentEnv(target, filepath.Dir(path))
	mergeEnvGaps(svc, compEnv)
	return true
}

// findRawService locates a service in the raw map by name, falling back
// to the only entry if there's exactly one service.
func findRawService(services map[string]rawServiceStruct, name string) (rawServiceStruct, bool) {
	if t, ok := services[name]; ok {
		return t, true
	}
	if len(services) == 1 {
		for k := range services {
			return services[k], true
		}
	}
	return rawServiceStruct{}, false
}

// buildComponentEnv merges env_file and inline environment from a raw
// service definition. Inline environment wins over env_file.
func buildComponentEnv(target rawServiceStruct, compDir string) map[string]string {
	compEnv := make(map[string]string)
	for _, ef := range parseEnvFileList(target.EnvFile) {
		if !filepath.IsAbs(ef) {
			ef = filepath.Join(compDir, ef)
		}
		for k, v := range loadEnvFile(ef) {
			compEnv[k] = v
		}
	}
	for k, v := range parseEnvironment(target.Environment) {
		compEnv[k] = v // inline environment wins over env_file
	}
	return compEnv
}

// mergeEnvGaps fills missing environment keys in svc from compEnv.
// composed.yaml entries always win (existing keys are never overwritten).
func mergeEnvGaps(svc *config.Service, compEnv map[string]string) {
	if len(compEnv) == 0 {
		return
	}
	if svc.Environment == nil {
		svc.Environment = make(map[string]string)
	}
	for k, v := range compEnv {
		if _, exists := svc.Environment[k]; !exists {
			svc.Environment[k] = v
		}
	}
}

// applyConfigVolumes applies user-declared volumes from composed.yaml onto the
// merged output. User volumes override chart-generated volumes of the same name.
func applyConfigVolumes(merged *compose.File, cfg *config.File) {
	for name, vol := range cfg.Volumes {
		merged.Volumes[name] = &compose.Volume{
			External: vol.External,
			Name:     vol.Name,
			Driver:   vol.Driver,
		}
	}
}

func labelServices(merged *compose.File, cfg *config.File) {
	for _, svc := range merged.Services {
		if svc.Labels == nil {
			svc.Labels = make(map[string]string)
		}
		svc.Labels["com.composed.managed"] = "true"
		svc.Labels["com.composed.project"] = cfg.Name
	}
}

// --- Service processors ---

// imageToCompose creates a compose fragment for a plain image service.
func imageToCompose(name string, svc *config.Service) *compose.File {
	f := compose.NewFile()
	cs := compose.NewService(svc.Image)
	cs.Command = svc.Command
	cs.Entrypoint = svc.Entrypoint
	cs.Ports = svc.Ports
	cs.Volumes = svc.Volumes
	cs.EnvFile = svc.EnvFile
	for k, v := range svc.Environment {
		cs.Environment[k] = v
	}
	for k, v := range svc.Labels {
		cs.Labels[k] = v
	}
	if svc.Healthcheck != nil {
		cs.Healthcheck = &compose.Healthcheck{
			Test:     svc.Healthcheck.Test,
			Interval: svc.Healthcheck.Interval,
			Timeout:  svc.Healthcheck.Timeout,
			Retries:  svc.Healthcheck.Retries,
		}
	}
	if svc.Restart != "" {
		cs.Restart = svc.Restart
	} else {
		cs.Restart = "unless-stopped"
	}
	f.Services[name] = cs

	// Auto-create named volumes
	for _, v := range svc.Volumes {
		parts := strings.SplitN(v, ":", 2)
		if len(parts) == 2 && !strings.HasPrefix(parts[0], "/") && !strings.HasPrefix(parts[0], ".") {
			f.Volumes[parts[0]] = &compose.Volume{}
		}
	}

	return f
}

// composeFragment loads an external compose file.
func composeFragment(svc *config.Service) (*compose.File, error) {
	path := svc.XComposeFile
	if path == "" {
		return nil, fmt.Errorf("compose service needs x-compose-file")
	}
	if !filepath.IsAbs(path) {
		dir := filepath.Dir(buildFile)
		path = filepath.Join(dir, path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read compose file %s: %w", path, err)
	}
	return parseComposeYAML(data)
}

// helmToCompose renders a Helm chart and translates to compose.
func helmToCompose(name string, svc *config.Service) (*compose.File, error) {
	h := svc.XHelm
	release := name

	var valueFiles []string
	if h.ValuesFile != "" {
		vfPath := h.ValuesFile
		if !filepath.IsAbs(vfPath) {
			vfPath = filepath.Join(filepath.Dir(buildFile), vfPath)
		}
		if _, err := os.Stat(vfPath); err != nil {
			return nil, fmt.Errorf("values_file %s: %w", vfPath, err)
		}
		valueFiles = append(valueFiles, vfPath)
		fmt.Fprintf(os.Stderr, "  Using values file %s\n", vfPath)
	}

	// Convert inline values to --set strings
	setValues := flattenValues("", h.Values)

	manifests, err := helm.Render(helm.RenderOpts{
		Chart:      h.Chart,
		Repo:       h.Repo,
		Version:    h.Version,
		Release:    release,
		ValueFiles: valueFiles,
		SetValues:  setValues,
	})
	if err != nil {
		return nil, fmt.Errorf("helm render: %w", err)
	}

	result, err := translate.Translate(manifests, translate.Opts{
		Project: name,
	})
	if err != nil {
		return nil, fmt.Errorf("translate: %w", err)
	}

	result.Report.Print(os.Stderr)
	return result.Compose, nil
}

// deepMerge merges src into dst recursively (src wins on conflict).
func deepMerge(dst, src map[string]interface{}) {
	for k, sv := range src {
		if dv, ok := dst[k]; ok {
			if dm, ok := dv.(map[string]interface{}); ok {
				if sm, ok := sv.(map[string]interface{}); ok {
					deepMerge(dm, sm)
					continue
				}
			}
		}
		dst[k] = sv
	}
}

// --- Helpers ---

// flattenValues flattens nested map to "key.subkey=value" pairs for Helm --set.
func flattenValues(prefix string, m map[string]interface{}) map[string]string {
	out := make(map[string]string)
	for k, v := range m {
		key := k
		if prefix != "" {
			key = prefix + "." + k
		}
		switch val := v.(type) {
		case map[string]interface{}:
			for fk, fv := range flattenValues(key, val) {
				out[fk] = fv
			}
		case string:
			out[key] = val
		case int:
			out[key] = fmt.Sprintf("%d", val)
		case float64:
			out[key] = fmt.Sprintf("%v", val)
		case bool:
			out[key] = fmt.Sprintf("%t", val)
		default:
			out[key] = fmt.Sprintf("%v", val)
		}
	}
	return out
}

// applyDependsOn adds depends_on entries from cross-service dependencies.
func applyDependsOn(frag *compose.File, deps []string, cfg *config.File) {
	for _, depName := range deps {
		depSvc, ok := cfg.Services[depName]
		if !ok {
			continue
		}

		// The target service name is the dependency name
		targetSvc := depName

		condition := "service_started"
		if depSvc.Healthcheck != nil {
			condition = "service_healthy"
		}

		for svcName, svc := range frag.Services {
			if svcName == targetSvc {
				continue
			}
			svc.DependsOn[targetSvc] = compose.DependsOnCondition{
				Condition: condition,
			}
		}
	}
}

// topoSort does a simple topological sort of services by depends_on.
func topoSort(cfg *config.File) []string {
	visited := make(map[string]bool)
	var order []string

	var visit func(name string)
	visit = func(name string) {
		if visited[name] {
			return
		}
		visited[name] = true
		svc := cfg.Services[name]
		for _, dep := range svc.DependsOn {
			if _, ok := cfg.Services[dep]; ok {
				visit(dep)
			}
		}
		order = append(order, name)
	}

	for name := range cfg.Services {
		visit(name)
	}
	return order
}

// parseComposeYAML parses a docker-compose.yaml into our compose model.
func parseComposeYAML(data []byte) (*compose.File, error) {
	var raw struct {
		Services map[string]rawServiceStruct `yaml:"services"`
		Volumes  map[string]interface{}      `yaml:"volumes"`
		Networks map[string]interface{}      `yaml:"networks"`
	}

	if err := yamlUnmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse compose yaml: %w", err)
	}

	f := compose.NewFile()

	for name := range raw.Services {
		f.Services[name] = parseRawService(raw.Services[name])
	}

	for name := range raw.Volumes {
		f.Volumes[name] = &compose.Volume{}
	}

	for name := range raw.Networks {
		f.Networks[name] = &compose.Network{}
	}

	return f, nil
}

type rawServiceStruct struct {
	Image       string            `yaml:"image"`
	Command     interface{}       `yaml:"command"`
	Entrypoint  interface{}       `yaml:"entrypoint"`
	Environment interface{}       `yaml:"environment"`
	EnvFile     interface{}       `yaml:"env_file"`
	Ports       []string          `yaml:"ports"`
	Volumes     []string          `yaml:"volumes"`
	DependsOn   interface{}       `yaml:"depends_on"`
	Restart     string            `yaml:"restart"`
	Labels      map[string]string `yaml:"labels"`
	XExports    map[string]string `yaml:"x-exports"`
	Healthcheck *struct {
		Test     interface{} `yaml:"test"`
		Interval string      `yaml:"interval"`
		Timeout  string      `yaml:"timeout"`
		Retries  int         `yaml:"retries"`
	} `yaml:"healthcheck"`
}

func parseRawService(svc rawServiceStruct) *compose.Service {
	cs := compose.NewService(svc.Image)
	cs.Ports = svc.Ports
	cs.Volumes = svc.Volumes
	cs.Restart = svc.Restart
	cs.Command = toStringSlice(svc.Command)
	cs.Entrypoint = toStringSlice(svc.Entrypoint)
	for k, v := range svc.Labels {
		cs.Labels[k] = v
	}

	for depName, cond := range parseDependsOn(svc.DependsOn) {
		cs.DependsOn[depName] = cond
	}

	for k, v := range parseEnvironment(svc.Environment) {
		cs.Environment[k] = v
	}

	cs.EnvFile = parseEnvFileList(svc.EnvFile)

	if svc.Healthcheck != nil {
		cs.Healthcheck = &compose.Healthcheck{
			Test:     toStringSlice(svc.Healthcheck.Test),
			Interval: svc.Healthcheck.Interval,
			Timeout:  svc.Healthcheck.Timeout,
			Retries:  svc.Healthcheck.Retries,
		}
	}

	return cs
}

func parseDependsOn(raw interface{}) map[string]compose.DependsOnCondition {
	result := make(map[string]compose.DependsOnCondition)
	switch dep := raw.(type) {
	case []interface{}:
		for _, item := range dep {
			depName := fmt.Sprintf("%v", item)
			result[depName] = compose.DependsOnCondition{Condition: "service_started"}
		}
	case map[string]interface{}:
		for depName, cond := range dep {
			condition := "service_started"
			if cm, ok := cond.(map[string]interface{}); ok {
				if c, ok := cm["condition"].(string); ok {
					condition = c
				}
			}
			result[depName] = compose.DependsOnCondition{Condition: condition}
		}
	}
	return result
}

func parseEnvironment(raw interface{}) map[string]string {
	result := make(map[string]string)
	switch env := raw.(type) {
	case map[string]interface{}:
		for k, v := range env {
			result[k] = fmt.Sprintf("%v", v)
		}
	case []interface{}:
		for _, item := range env {
			s := fmt.Sprintf("%v", item)
			if k, v, ok := strings.Cut(s, "="); ok {
				result[k] = v
			}
		}
	}
	return result
}

func toStringSlice(v interface{}) []string {
	switch val := v.(type) {
	case []interface{}:
		out := make([]string, len(val))
		for i, item := range val {
			out[i] = fmt.Sprintf("%v", item)
		}
		return out
	case string:
		if val == "" {
			return nil
		}
		return []string{val}
	default:
		return nil
	}
}

// parseEnvFileList extracts a list of env_file paths from the raw YAML value.
// Supports string ("foo.env"), list of strings, and list of objects with "path".
func parseEnvFileList(raw interface{}) []string {
	switch v := raw.(type) {
	case string:
		return []string{v}
	case []interface{}:
		var out []string
		for _, item := range v {
			switch entry := item.(type) {
			case string:
				out = append(out, entry)
			case map[string]interface{}:
				if p, ok := entry["path"].(string); ok {
					out = append(out, p)
				}
			}
		}
		return out
	}
	return nil
}

// loadEnvFile reads a .env file and returns KEY=VALUE pairs.
// Skips blank lines, comments (#), and supports matched quoting.
func loadEnvFile(path string) map[string]string {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "Warning: env_file %q not found, skipping\n", path)
		}
		return nil
	}
	defer f.Close() //nolint:errcheck // read-only file, close error is harmless

	result := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Support `export KEY=VAL` syntax
		line = strings.TrimPrefix(line, "export ")
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		// Strip matched quote pairs only
		if (strings.HasPrefix(v, `"`) && strings.HasSuffix(v, `"`)) ||
			(strings.HasPrefix(v, `'`) && strings.HasSuffix(v, `'`)) {
			v = v[1 : len(v)-1]
		}
		result[k] = v
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: error reading env_file %q: %v\n", path, err)
	}
	return result
}

func dockerCompose(args ...string) error {
	dockerPath, err := exec.LookPath("docker")
	if err != nil {
		return fmt.Errorf("docker not found in PATH: %w", err)
	}
	allArgs := append([]string{"-f", buildOutput}, args...)
	cmd := exec.Command(dockerPath, append([]string{"compose"}, allArgs...)...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func yamlUnmarshal(data []byte, v interface{}) error {
	return yaml.Unmarshal(data, v)
}
