package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/docker-x/composed/internal/compose"
	"github.com/docker-x/composed/internal/config"
	"github.com/docker-x/composed/internal/helm"
	"github.com/docker-x/composed/internal/merge"
	"github.com/docker-x/composed/internal/translate"
	"gopkg.in/yaml.v3"
	"github.com/spf13/cobra"
)

var buildCmd = &cobra.Command{
	Use:   "build",
	Short: "Build a mega docker-compose.yaml from a composed.yaml config",
	Long: `Read a composed.yaml (a Docker Compose file with x- extensions) and
produce a single merged docker-compose.yaml. Helm charts are rendered,
compose includes are merged, and cross-references are resolved.

Services can reference each other via ${service.export_key} syntax
using x-exports, similar to Terraform or CDK.

Examples:
  # Build from config
  composed build -f composed.yaml -o docker-compose.yaml

  # Build and immediately start
  composed up -f composed.yaml`,
	RunE: runBuild,
}

var (
	buildFile   string
	buildOutput string
	upFile      string
	upOutput    string
	downOutput  string
)

var upCmd = &cobra.Command{
	Use:   "up",
	Short: "Build and start the stack via docker compose up",
	RunE:  runUp,
}

var downCmd = &cobra.Command{
	Use:   "down",
	Short: "Stop the stack via docker compose down",
	RunE:  runDown,
}

func init() {
	buildCmd.Flags().StringVarP(&buildFile, "file", "f", "composed.yaml", "Config file")
	buildCmd.Flags().StringVarP(&buildOutput, "output", "o", "docker-compose.yaml", "Output file (- for stdout)")
	rootCmd.AddCommand(buildCmd)

	upCmd.Flags().StringVarP(&upFile, "file", "f", "composed.yaml", "Config file")
	upCmd.Flags().StringVarP(&upOutput, "output", "o", "docker-compose.yaml", "Output file")
	downCmd.Flags().StringVarP(&downOutput, "output", "o", "docker-compose.yaml", "Compose file")
	rootCmd.AddCommand(upCmd)
	rootCmd.AddCommand(downCmd)
}

func runBuild(cmd *cobra.Command, args []string) error {
	buildFile = resolveConfig(cmd, buildFile)
	return doBuild()
}

func runUp(cmd *cobra.Command, args []string) error {
	buildFile = resolveConfig(cmd, upFile)
	buildOutput = upOutput
	if err := doBuild(); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Starting stack with docker compose up -d ...\n")
	return dockerCompose("up", "-d")
}

func runDown(cmd *cobra.Command, args []string) error {
	buildOutput = downOutput
	fmt.Fprintf(os.Stderr, "Stopping stack ...\n")
	return dockerCompose("down")
}

func doBuild() error {
	// 1. Load config
	cfg, err := config.Load(buildFile)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	// 2. Resolve cross-references
	if err := cfg.ResolveRefs(); err != nil {
		return fmt.Errorf("resolve refs: %w", err)
	}

	// 3. Process each service → compose fragment
	var fragments []*compose.File

	// Process in dependency order
	order := topoSort(cfg)
	for _, name := range order {
		svc := cfg.Services[name]
		svcType := config.ServiceType(&svc)
		fmt.Fprintf(os.Stderr, "Processing service %q (type: %s)...\n", name, svcType)

		var frag *compose.File
		var err error

		switch svcType {
		case "image":
			frag = imageToCompose(name, &svc)
		case "compose":
			frag, err = composeFragment(name, &svc)
		case "helm":
			frag, err = helmToCompose(name, &svc)
		default:
			return fmt.Errorf("service %q: unknown type %q", name, svcType)
		}
		if err != nil {
			return fmt.Errorf("service %q: %w", name, err)
		}

		// Apply cross-service depends_on
		if len(svc.DependsOn) > 0 && frag != nil {
			applyDependsOn(frag, name, svc.DependsOn, cfg)
		}

		fragments = append(fragments, frag)
	}

	// 4. Merge all fragments
	merged := merge.Merge(cfg.Name, fragments...)

	// 5. Label all services as composed-managed
	for _, svc := range merged.Services {
		if svc.Labels == nil {
			svc.Labels = make(map[string]string)
		}
		svc.Labels["com.composed.managed"] = "true"
		svc.Labels["com.composed.project"] = cfg.Name
	}

	// 6. Set header
	names := make([]string, 0, len(cfg.Services))
	for n := range cfg.Services {
		names = append(names, n)
	}
	merged.Header = fmt.Sprintf("Generated by composed from %s\n# Components: %s",
		buildFile, strings.Join(names, ", "))

	// 6. Emit
	out, err := compose.Emit(merged)
	if err != nil {
		return fmt.Errorf("emit: %w", err)
	}

	if buildOutput == "-" {
		fmt.Print(out)
		return nil
	}

	if err := os.WriteFile(buildOutput, []byte(out), 0644); err != nil {
		return fmt.Errorf("write %s: %w", buildOutput, err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %s (%d services, %d volumes)\n",
		buildOutput, len(merged.Services), len(merged.Volumes))
	return nil
}

// --- Service processors ---

// imageToCompose creates a compose fragment for a plain image service.
func imageToCompose(name string, svc *config.Service) *compose.File {
	f := compose.NewFile()
	cs := compose.NewService(svc.Image)
	cs.Command = svc.Command
	cs.Entrypoint = svc.Entrypoint
	cs.Ports = svc.Ports
	cs.Volumes = svc.Volumes
	for k, v := range svc.Environment {
		cs.Environment[k] = v
	}
	for k, v := range svc.Labels {
		cs.Labels[k] = v
	}
	if svc.Healthcheck != nil {
		cs.Healthcheck = &compose.Healthcheck{
			Test:     svc.Healthcheck.Test,
			Interval: svc.Healthcheck.Interval,
			Timeout:  svc.Healthcheck.Timeout,
			Retries:  svc.Healthcheck.Retries,
		}
	}
	cs.Restart = "unless-stopped"
	f.Services[name] = cs

	// Auto-create named volumes
	for _, v := range svc.Volumes {
		parts := strings.SplitN(v, ":", 2)
		if len(parts) == 2 && !strings.HasPrefix(parts[0], "/") && !strings.HasPrefix(parts[0], ".") {
			f.Volumes[parts[0]] = &compose.Volume{}
		}
	}

	return f
}

// composeFragment loads an external compose file.
func composeFragment(name string, svc *config.Service) (*compose.File, error) {
	path := svc.XComposeFile
	if path == "" {
		return nil, fmt.Errorf("compose service needs x-compose-file")
	}
	if !filepath.IsAbs(path) {
		dir := filepath.Dir(buildFile)
		path = filepath.Join(dir, path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read compose file %s: %w", path, err)
	}
	return parseComposeYAML(data)
}

// helmToCompose renders a Helm chart and translates to compose.
func helmToCompose(name string, svc *config.Service) (*compose.File, error) {
	h := svc.XHelm
	release := name

	var valueFiles []string
	if h.ValuesFile != "" {
		vfPath := h.ValuesFile
		if !filepath.IsAbs(vfPath) {
			vfPath = filepath.Join(filepath.Dir(buildFile), vfPath)
		}
		if _, err := os.Stat(vfPath); err != nil {
			return nil, fmt.Errorf("values_file %s: %w", vfPath, err)
		}
		valueFiles = append(valueFiles, vfPath)
		fmt.Fprintf(os.Stderr, "  Using values file %s\n", vfPath)
	}

	// Convert inline values to --set strings
	setValues := flattenValues("", h.Values)

	manifests, err := helm.Render(helm.RenderOpts{
		Chart:      h.Chart,
		Repo:       h.Repo,
		Version:    h.Version,
		Release:    release,
		ValueFiles: valueFiles,
		SetValues:  setValues,
	})
	if err != nil {
		return nil, fmt.Errorf("helm render: %w", err)
	}

	result, err := translate.Translate(manifests, translate.Opts{
		Project: name,
	})
	if err != nil {
		return nil, fmt.Errorf("translate: %w", err)
	}

	result.Report.Print(os.Stderr)
	return result.Compose, nil
}

// deepMerge merges src into dst recursively (src wins on conflict).
func deepMerge(dst, src map[string]interface{}) {
	for k, sv := range src {
		if dv, ok := dst[k]; ok {
			if dm, ok := dv.(map[string]interface{}); ok {
				if sm, ok := sv.(map[string]interface{}); ok {
					deepMerge(dm, sm)
					continue
				}
			}
		}
		dst[k] = sv
	}
}

// --- Helpers ---

// flattenValues flattens nested map to "key.subkey=value" pairs for Helm --set.
func flattenValues(prefix string, m map[string]interface{}) map[string]string {
	out := make(map[string]string)
	for k, v := range m {
		key := k
		if prefix != "" {
			key = prefix + "." + k
		}
		switch val := v.(type) {
		case map[string]interface{}:
			for fk, fv := range flattenValues(key, val) {
				out[fk] = fv
			}
		case string:
			out[key] = val
		case int:
			out[key] = fmt.Sprintf("%d", val)
		case float64:
			out[key] = fmt.Sprintf("%v", val)
		case bool:
			out[key] = fmt.Sprintf("%t", val)
		default:
			out[key] = fmt.Sprintf("%v", val)
		}
	}
	return out
}

// applyDependsOn adds depends_on entries from cross-service dependencies.
func applyDependsOn(frag *compose.File, selfName string, deps []string, cfg *config.File) {
	for _, depName := range deps {
		depSvc, ok := cfg.Services[depName]
		if !ok {
			continue
		}

		// The target service name is the dependency name
		targetSvc := depName

		condition := "service_started"
		if depSvc.Healthcheck != nil {
			condition = "service_healthy"
		}

		for svcName, svc := range frag.Services {
			if svcName == targetSvc {
				continue
			}
			svc.DependsOn[targetSvc] = compose.DependsOnCondition{
				Condition: condition,
			}
		}
	}
}

// topoSort does a simple topological sort of services by depends_on.
func topoSort(cfg *config.File) []string {
	visited := make(map[string]bool)
	var order []string

	var visit func(name string)
	visit = func(name string) {
		if visited[name] {
			return
		}
		visited[name] = true
		svc := cfg.Services[name]
		for _, dep := range svc.DependsOn {
			if _, ok := cfg.Services[dep]; ok {
				visit(dep)
			}
		}
		order = append(order, name)
	}

	for name := range cfg.Services {
		visit(name)
	}
	return order
}

// parseComposeYAML parses a docker-compose.yaml into our compose model.
func parseComposeYAML(data []byte) (*compose.File, error) {
	var raw struct {
		Services map[string]struct {
			Image       string            `yaml:"image"`
			Command     interface{}       `yaml:"command"`
			Entrypoint  interface{}       `yaml:"entrypoint"`
			Environment interface{}       `yaml:"environment"`
			Ports       []string          `yaml:"ports"`
			Volumes     []string          `yaml:"volumes"`
			DependsOn   interface{}       `yaml:"depends_on"`
			Restart     string            `yaml:"restart"`
			Labels      map[string]string `yaml:"labels"`
			Healthcheck *struct {
				Test     interface{} `yaml:"test"`
				Interval string      `yaml:"interval"`
				Timeout  string      `yaml:"timeout"`
				Retries  int         `yaml:"retries"`
			} `yaml:"healthcheck"`
		} `yaml:"services"`
		Volumes  map[string]interface{} `yaml:"volumes"`
		Networks map[string]interface{} `yaml:"networks"`
	}

	if err := yamlUnmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse compose yaml: %w", err)
	}

	f := compose.NewFile()

	for name, svc := range raw.Services {
		cs := compose.NewService(svc.Image)
		cs.Ports = svc.Ports
		cs.Volumes = svc.Volumes
		cs.Restart = svc.Restart
		cs.Command = toStringSlice(svc.Command)
		cs.Entrypoint = toStringSlice(svc.Entrypoint)
		for k, v := range svc.Labels {
			cs.Labels[k] = v
		}

		// Parse environment (can be map or list)
		switch env := svc.Environment.(type) {
		case map[string]interface{}:
			for k, v := range env {
				cs.Environment[k] = fmt.Sprintf("%v", v)
			}
		case []interface{}:
			for _, item := range env {
				s := fmt.Sprintf("%v", item)
				if k, v, ok := strings.Cut(s, "="); ok {
					cs.Environment[k] = v
				}
			}
		}

		if svc.Healthcheck != nil {
			cs.Healthcheck = &compose.Healthcheck{
				Test:     toStringSlice(svc.Healthcheck.Test),
				Interval: svc.Healthcheck.Interval,
				Timeout:  svc.Healthcheck.Timeout,
				Retries:  svc.Healthcheck.Retries,
			}
		}

		f.Services[name] = cs
	}

	for name := range raw.Volumes {
		f.Volumes[name] = &compose.Volume{}
	}

	for name := range raw.Networks {
		f.Networks[name] = &compose.Network{}
	}

	return f, nil
}

func toStringSlice(v interface{}) []string {
	switch val := v.(type) {
	case []interface{}:
		out := make([]string, len(val))
		for i, item := range val {
			out[i] = fmt.Sprintf("%v", item)
		}
		return out
	case string:
		if val == "" {
			return nil
		}
		return []string{val}
	default:
		return nil
	}
}

func dockerCompose(args ...string) error {
	allArgs := append([]string{"-f", buildOutput}, args...)
	cmd := exec.Command("docker", append([]string{"compose"}, allArgs...)...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func yamlUnmarshal(data []byte, v interface{}) error {
	return yaml.Unmarshal(data, v)
}
